;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Damage.Type.Fire",NewTagName="Damage.Type.Elemental.Fire")
+GameplayTagRedirects=(OldTagName="Damage.Type.Cold",NewTagName="Damage.Type.Elemental.Cold")
+GameplayTagRedirects=(OldTagName="Damage.Type.Lightning",NewTagName="Damage.Type.Elemental.Lightning")
+GameplayTagRedirects=(OldTagName="GameState.Load",NewTagName="Request.Save.Load")
+GameplayTagRedirects=(OldTagName="GameState.MainMenu",NewTagName="Request.Save.MainMenu")
+GameplayTagRedirects=(OldTagName="GameState.Save",NewTagName="Request.Save.Save")
+GameplayTagRedirects=(OldTagName="GameState.SaveLoad",NewTagName="Request.Save.SaveLoad")
+GameplayTagRedirects=(OldTagName="GameState.Started",NewTagName="Request.Save.Started")
+GameplayTagRedirects=(OldTagName="Request.Save.Started",NewTagName="Request.Save.Full")
+GameplayTagRedirects=(OldTagName="Request.Deck.Remove",NewTagName="Request.Deck.Discard")
+GameplayTagRedirects=(OldTagName="Damage.Type.Chaos",NewTagName="Damage.Element.Chaos")
+GameplayTagRedirects=(OldTagName="Damage.Type.Elemental.Cold",NewTagName="Damage.Element.Elemental.Cold")
+GameplayTagRedirects=(OldTagName="Damage.Type.Elemental.Fire",NewTagName="Damage.Element.Elemental.Fire")
+GameplayTagRedirects=(OldTagName="Damage.Type.Elemental.Lightning",NewTagName="Damage.Element.Elemental.Lightning")
+GameplayTagRedirects=(OldTagName="Damage.Type.Elemental",NewTagName="Damage.Element.Elemental")
+GameplayTagRedirects=(OldTagName="Damage.Type.Physical",NewTagName="Damage.Element.Physical")
+GameplayTagRedirects=(OldTagName="Damage.Type",NewTagName="Damage.Element")
+GameplayTagList=(Tag="Component.Modifiers",DevComment="")
+GameplayTagList=(Tag="Damage.Element.Chaos",DevComment="")
+GameplayTagList=(Tag="Damage.Element.Elemental.Cold",DevComment="")
+GameplayTagList=(Tag="Damage.Element.Elemental.Fire",DevComment="")
+GameplayTagList=(Tag="Damage.Element.Elemental.Lightning",DevComment="")
+GameplayTagList=(Tag="Damage.Element.Physical",DevComment="")
+GameplayTagList=(Tag="Damage.SetByCaller",DevComment="")
+GameplayTagList=(Tag="Dungeon",DevComment="")
+GameplayTagList=(Tag="Enemies",DevComment="")
+GameplayTagList=(Tag="Enemies.Bosses.Death",DevComment="")
+GameplayTagList=(Tag="Enemies.Bosses.Engage",DevComment="")
+GameplayTagList=(Tag="Mod.Defense.DamageTaken",DevComment="")
+GameplayTagList=(Tag="Mod.Defense.Glancing",DevComment="")
+GameplayTagList=(Tag="Mod.Defense.ManaDamage",DevComment="")
+GameplayTagList=(Tag="Mod.Defense.Mitigation",DevComment="")
+GameplayTagList=(Tag="Mod.Offense.CastSpeed",DevComment="")
+GameplayTagList=(Tag="Mod.Offense.Critical",DevComment="")
+GameplayTagList=(Tag="Mod.Offense.Damage",DevComment="")
+GameplayTagList=(Tag="Mod.Offense.ImplicitDamage",DevComment="Base scaling value of a weapon or character")
+GameplayTagList=(Tag="Mod.Stat.Armour",DevComment="")
+GameplayTagList=(Tag="Mod.Stat.Evasion",DevComment="")
+GameplayTagList=(Tag="Mod.Stat.Instinct",DevComment="")
+GameplayTagList=(Tag="Mod.Stat.Level",DevComment="")
+GameplayTagList=(Tag="Mod.Stat.Life",DevComment="")
+GameplayTagList=(Tag="Mod.Stat.Mana",DevComment="")
+GameplayTagList=(Tag="Mod.Stat.Movement",DevComment="")
+GameplayTagList=(Tag="Mod.Stat.Strength",DevComment="")
+GameplayTagList=(Tag="Mod.Stat.Willpower",DevComment="")
+GameplayTagList=(Tag="Mod.Utility.Area",DevComment="")
+GameplayTagList=(Tag="Mod.Utility.CardBias",DevComment="")
+GameplayTagList=(Tag="Mod.Utility.Cost",DevComment="")
+GameplayTagList=(Tag="Mod.Utility.Duration",DevComment="")
+GameplayTagList=(Tag="Mod.Utility.ItemRarity",DevComment="")
+GameplayTagList=(Tag="Player",DevComment="")
+GameplayTagList=(Tag="Player.Death",DevComment="")
+GameplayTagList=(Tag="Player.HealthChanged",DevComment="")
+GameplayTagList=(Tag="Player.ManaChanged",DevComment="")
+GameplayTagList=(Tag="Player.Stats.OnExpGained",DevComment="")
+GameplayTagList=(Tag="Player.Stats.OnLevelUp",DevComment="")
+GameplayTagList=(Tag="Request.Deck.Discard",DevComment="")
+GameplayTagList=(Tag="Request.Deck.Draw",DevComment="")
+GameplayTagList=(Tag="Request.Deck.Reset",DevComment="")
+GameplayTagList=(Tag="Resource.Shield",DevComment="")
+GameplayTagList=(Tag="Status.Electrified",DevComment="")
+GameplayTagList=(Tag="Type.Area",DevComment="")
+GameplayTagList=(Tag="Type.Buff",DevComment="")
+GameplayTagList=(Tag="Type.Channelling",DevComment="")
+GameplayTagList=(Tag="Type.Defensive",DevComment="")
+GameplayTagList=(Tag="Type.DoT",DevComment="")
+GameplayTagList=(Tag="Type.Melee",DevComment="")
+GameplayTagList=(Tag="Type.Projectile",DevComment="")
